### ISSUE TITLE
Build broken on Develop: filter_cooldown_targets_adaptive missing from target_failure_tracker (regression from PR #1209)

### ISSUE THREAD

**Issue by stservice** [stSoftwareAU/NEAT-AI-Discovery#1212]
## Summary

The `Develop` branch of NEAT-AI-Discovery does not compile. Every GRQ node that
runs `ensure_neat_ai_discovery.sh` against v0.74.46 is failing with the same
error, causing a fleet-wide regression (stSoftwareAU/GRQ#2342).

## Build error

```
error[E0432]: unresolved import `crate::analysis::target_failure_tracker::filter_cooldown_targets_adaptive`
   --> src/analysis/neuron/preparation.rs:215:34
    |
215 |         filter_cooldown_targets, filter_cooldown_targets_adaptive, global_tracker,
    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |                                  |
    |                                  no `filter_cooldown_targets_adaptive` in `analysis::target_failure_tracker`
    |                                  help: a similar name exists in the module: `filter_cooldown_targets`

error[E0432]: unresolved import `crate::analysis::target_failure_tracker::filter_cooldown_targets_adaptive`
   --> src/analysis/synapse/orchestration.rs:216:34
    |
216 |         filter_cooldown_targets, filter_cooldown_targets_adaptive, global_tracker,
    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |                                  |
    |                                  no `filter_cooldown_targets_adaptive` in `analysis::target_failure_tracker`
    |                                  help: a similar name exists in the module: `filter_cooldown_targets`

error: could not compile `neat_ai_discovery` (lib) due to 2 previous errors
```

## Root cause

PR #1209 (`b9f9cedc` — "Adaptive target-cooldown relaxation during drought (Issue #1204)")
added call sites for `filter_cooldown_targets_adaptive` in:

- `src/analysis/neuron/preparation.rs:215` and `:235`
- `src/analysis/synapse/orchestration.rs:216` and `:235`

but did **not** add the corresponding `pub fn filter_cooldown_targets_adaptive`
to `src/analysis/target_failure_tracker.rs`. That file still only exposes
`filter_cooldown_targets` (line 277) and `global_tracker` (line 304).

## Expected fix

Add `pub fn filter_cooldown_targets_adaptive(focus_order, tracker, current_epoch, mode, drought_failures)` to `src/analysis/target_failure_tracker.rs`, matching the signature already
used by the two call sites:

```rust
filter_cooldown_targets_adaptive(
    focus_order,
    &tracker_lock,
    current_epoch,
    mode,
    drought_failures,
)
```

Behaviour should match the intent of Issue #1204 (relax the cooldown filter
during a drought, based on `mode` and the `drought_failures` streak), and tests
should be added under `target_failure_tracker.rs` alongside the existing
`filter_cooldown_targets_*` unit tests.

## Impact

Fleet-wide GRQ outage — every node fails at the `ensure_neat_ai_discovery.sh`
build step with exit code 101. See stSoftwareAU/GRQ#2342 and the affected logs
in `stSoftwareAU/GRQ-logs/` (GRQ-10-rocket, GRQ-13-rocket, GRQ-21-rocket,
GRQ-25-elephant, …). All blocked behind this single missing symbol.

**Comment by VibeCoderST** [comment]
Pull request https://github.com/stSoftwareAU/NEAT-AI-Discovery/pull/1213 has been created to address this issue.
